spring.application.name=reclamos
server.port=8081

# Configuración de Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5420/paris_marketplace?currentSchema=reclamos_schema
spring.datasource.username=postgres
spring.datasource.password=tu_contraseña_aqui

# Crear/Actualizar tablas de forma automática
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true